---
name: DateTime-TimeZone-HPUX
version: 1.03
author:
  - 'Olivier Mengué <dolmen@cpan.org>'
abstract: Handles timezones defined at the operating system level on HP-UX
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  DateTime::TimeZone: '>=0.87'
  File::Basename: 0
  Test::More: 0
requires:
  Carp: 0
  DateTime::TimeZone: '>=1.04'
configure_requires:
  Module::Build: 0.35
provides:
  DateTime::TimeZone::HPUX:
    file: lib/DateTime/TimeZone/HPUX.pm
    version: 1.03
  DateTime::TimeZone::Local::hpux:
    file: lib/DateTime/TimeZone/Local/hpux.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
